name: GitHub Pages Deploy

on:
  push:
    branches: [ "static-site" ]

jobs:
  build:
    defaults:
        run:
          working-directory: ./portfolio-site

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build site
      run: lein build-site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
          path: build_outputs_folder/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
